agent:
  name: "AutonomousAgent"
  goal: "Research and develop a comprehensive analysis of current AI safety approaches, categorize them by methodology, evaluate their effectiveness, and propose potential improvements or novel approaches. Document findings in a structured format that could serve as a reference guide."
  reflection_interval: 0.04  # (in hours)
  action_interval: 0.008  # (in hours)

model:
  provider: "openai"
  model_id: "gpt-4o-2024-08-06"


memory:
  max_tokens: 16000
  structure:
    - "Agent Identity and Goal"
    - "Progress Summary"
    - "Recent Actions and Outcomes"
    - "Next Steps and Planning"
    - "Insights and Learnings"