agent:
  name: "PhysicsArticleCurator"
  goal: "Find, summarize, categorize, and score the latest physics articles from reputable sources, creating a searchable database of physics research and news."
  action_interval: 1  # (in hours)

model:
  provider: "openai"
  model_id: "gpt-4o"
  web_search_enabled: true
  max_search_tokens: 4000
  max_analysis_tokens: 2000

memory:
  max_tokens: 4000
  structure:
    - "Agent Identity and Goal"
    - "Recent Articles"
    - "Search Topics"
    - "Statistics"