version: '3'

services:
  physics-agent:
    build: .
    container_name: physics-article-curator
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./web:/app/web
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Uncomment to override config values
      # - AGENT_GOAL=Your custom goal here
      # - RUN_ONCE=false
      # - WEB_ONLY=false
      # - DEBUG=false
    restart: unless-stopped 